// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYw47uMjwxtdL6ze9WSdhkI0k_SAhAt5c',
    appId: '1:742510803148:web:92df74ca1d6dfefd00ea69',
    messagingSenderId: '742510803148',
    projectId: 'xupstore-aa3f8',
    authDomain: 'xupstore-aa3f8.firebaseapp.com',
    storageBucket: 'xupstore-aa3f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnPEsB8ar80mxxnUQthqgIXRBYDTmyac',
    appId: '1:742510803148:android:2392492ae31f151200ea69',
    messagingSenderId: '742510803148',
    projectId: 'xupstore-aa3f8',
    storageBucket: 'xupstore-aa3f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt1Ad2zPkeUA2gFuYyxsjvcv1DKGUZ18o',
    appId: '1:742510803148:ios:47122b82d15db68100ea69',
    messagingSenderId: '742510803148',
    projectId: 'xupstore-aa3f8',
    storageBucket: 'xupstore-aa3f8.appspot.com',
    iosBundleId: 'com.example.xupstore',
  );
}
